package com.com253.payrollsystem.GUI.Panels;

import com.com253.payrollsystem.Model.Employee;
import com.com253.payrollsystem.Model.TimeRecord;
import com.com253.payrollsystem.Model.EmployeeTypes.Contractual;
import com.com253.payrollsystem.Model.EmployeeTypes.PartTimer;
import com.com253.payrollsystem.Model.EmployeeTypes.Probationary;
import com.com253.payrollsystem.Model.EmployeeTypes.Regular;
import com.com253.payrollsystem.Service.WorkingDayCalculator;

/**
 *
 * @author Jaszi
 */
public class EmployeeInfo extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeInfo
     */
    public EmployeeInfo() {
        initComponents();
        initializeDefaults();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        employeeIdLabel = new javax.swing.JLabel();
        employeeIdField = new javax.swing.JTextField();
        fullNameLabel = new javax.swing.JLabel();
        fullNameField = new javax.swing.JTextField();
        rateLabel = new javax.swing.JLabel();
        rateField = new javax.swing.JTextField();
        employeeTypeLabel = new javax.swing.JLabel();
        employeeTypeComboBox = new javax.swing.JComboBox<>();
        cutoffLabel = new javax.swing.JLabel();
        cutoffComboBox = new javax.swing.JComboBox<>();
        loanDeductionLabel = new javax.swing.JLabel();
        loanDeductionField = new javax.swing.JTextField();
        detailsSeparator = new javax.swing.JSeparator();
        timeRecordLabel = new javax.swing.JLabel();
        timeRecordTable = new com.com253.payrollsystem.GUI.Components.Table();

        setBackground(new java.awt.Color(10, 12, 20));
        setMaximumSize(new java.awt.Dimension(800, 700));

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("EMPLOYEE INFORMATION");

        employeeIdLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        employeeIdLabel.setForeground(new java.awt.Color(120, 135, 170));
        employeeIdLabel.setText("Employee ID");

        employeeIdField.setBackground(new java.awt.Color(22, 28, 48));
        employeeIdField.setForeground(new java.awt.Color(255, 255, 255));
        employeeIdField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));
        employeeIdField.addActionListener(this::employeeIdFieldActionPerformed);

        fullNameLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        fullNameLabel.setForeground(new java.awt.Color(120, 135, 170));
        fullNameLabel.setText("Full Name");

        fullNameField.setBackground(new java.awt.Color(22, 28, 48));
        fullNameField.setForeground(new java.awt.Color(255, 255, 255));
        fullNameField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));
        fullNameField.addActionListener(this::fullNameFieldActionPerformed);

        rateLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        rateLabel.setForeground(new java.awt.Color(120, 135, 170));
        rateLabel.setText("Rate (PHP)");

        rateField.setBackground(new java.awt.Color(22, 28, 48));
        rateField.setForeground(new java.awt.Color(255, 255, 255));
        rateField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));

        employeeTypeLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        employeeTypeLabel.setForeground(new java.awt.Color(120, 135, 170));
        employeeTypeLabel.setText("Employee Type");

        employeeTypeComboBox.setBackground(new java.awt.Color(22, 28, 48));
        employeeTypeComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        employeeTypeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        employeeTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        employeeTypeComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));
        employeeTypeComboBox.addActionListener(this::employeeTypeComboBoxActionPerformed);

        cutoffLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cutoffLabel.setForeground(new java.awt.Color(120, 135, 170));
        cutoffLabel.setText("Cut-off");

        cutoffComboBox.setBackground(new java.awt.Color(22, 28, 48));
        cutoffComboBox.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cutoffComboBox.setForeground(new java.awt.Color(255, 255, 255));
        cutoffComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cutoffComboBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));

        loanDeductionLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        loanDeductionLabel.setForeground(new java.awt.Color(120, 135, 170));
        loanDeductionLabel.setText("Loan Deduction");

        loanDeductionField.setBackground(new java.awt.Color(22, 28, 48));
        loanDeductionField.setForeground(new java.awt.Color(255, 255, 255));
        loanDeductionField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));

        timeRecordLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        timeRecordLabel.setForeground(new java.awt.Color(120, 135, 170));
        timeRecordLabel.setText("Time Record");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loanDeductionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(loanDeductionField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(detailsSeparator)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fullNameLabel)
                                .addGap(82, 82, 82)
                                .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cutoffLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(cutoffComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(employeeIdLabel)
                                .addGap(68, 68, 68)
                                .addComponent(employeeIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(employeeTypeLabel)
                                .addGap(52, 52, 52)
                                .addComponent(employeeTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(timeRecordLabel))
                    .addComponent(timeRecordTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(titleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(employeeIdLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(employeeIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(employeeTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(employeeTypeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullNameLabel)
                    .addComponent(fullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cutoffComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cutoffLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rateLabel)
                            .addComponent(rateField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(detailsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(loanDeductionLabel)
                    .addComponent(loanDeductionField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addComponent(timeRecordLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(timeRecordTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fullNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullNameFieldActionPerformed

    private void employeeIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeIdFieldActionPerformed

    private void employeeTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeTypeComboBoxActionPerformed
        updateRateLabel();
    }//GEN-LAST:event_employeeTypeComboBoxActionPerformed

    private void initializeDefaults() {
        employeeTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[] {"Regular", "Probationary", "Contractual", "PartTimer"}
        ));

        cutoffComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(
            new String[] {"1st Cut-off (1st-15th)", "2nd Cut-off (16th-30th)"}
        ));

        cutoffComboBox.addActionListener(evt -> applySelectedCutoffToTable());

        updateRateLabel();
        applySelectedCutoffToTable();
    }

    private void updateRateLabel() {
        String selectedType = (String) employeeTypeComboBox.getSelectedItem();
        if ("PartTimer".equals(selectedType)) {
            rateLabel.setText("Hourly Rate (PHP)");
        } else {
            rateLabel.setText("Monthly Rate (PHP)");
        }
    }

    public Employee buildEmployeeFromInput() {
        String employeeId = employeeIdField.getText().trim();
        String fullName = fullNameField.getText().trim();
        String selectedType = (String) employeeTypeComboBox.getSelectedItem();
        String rateText = rateField.getText().trim();

        if (employeeId.isEmpty()) {
            throw new IllegalArgumentException("Employee ID is required.");
        }
        if (fullName.isEmpty()) {
            throw new IllegalArgumentException("Full Name is required.");
        }
        if (rateText.isEmpty()) {
            throw new IllegalArgumentException("Rate is required.");
        }

        double rate;
        try {
            rate = Double.parseDouble(rateText);
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Rate must be a valid number.");
        }

        if (rate <= 0) {
            throw new IllegalArgumentException("Rate must be greater than zero.");
        }

        return switch (selectedType) {
            case "Regular" -> new Regular(employeeId, fullName, rate);
            case "Probationary" -> new Probationary(employeeId, fullName, rate);
            case "Contractual" -> new Contractual(employeeId, fullName, rate);
            case "PartTimer" -> new PartTimer(employeeId, fullName, rate);
            default -> throw new IllegalArgumentException("Please select a valid employee type.");
        };
    }

    public String getCutoffPeriod() {
        return getSelectedCutoffCode();
    }

    public double getLoanDeduction() {
        String loanText = loanDeductionField.getText().trim();
        if (loanText.isEmpty()) {
            return 0.0;
        }

        try {
            double value = Double.parseDouble(loanText);
            if (value < 0) {
                throw new IllegalArgumentException("Loan deduction cannot be negative.");
            }
            return value;
        } catch (NumberFormatException ex) {
            throw new IllegalArgumentException("Loan deduction must be a valid number.");
        }
    }

    public TimeRecord[] getTimeRecords() {
        return timeRecordTable.buildTimeRecords();
    }

    public void resetInputs() {
        employeeIdField.setText("");
        fullNameField.setText("");
        rateField.setText("");
        loanDeductionField.setText("");
        employeeTypeComboBox.setSelectedIndex(0);
        cutoffComboBox.setSelectedIndex(0);
        applySelectedCutoffToTable();
        updateRateLabel();
    }

    private void applySelectedCutoffToTable() {
        int[] workingDays = getWorkingDays(getSelectedCutoffCode());
        timeRecordTable.setWorkingDays(workingDays);
    }

    private String getSelectedCutoffCode() {
        int selectedIndex = cutoffComboBox.getSelectedIndex();
        return selectedIndex == 1 ? "16th-30th" : "1st-15th";
    }

    private int[] getWorkingDays(String cutOffPeriod) {
        return WorkingDayCalculator.getWorkingDaysForCurrentMonth(cutOffPeriod);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> employeeTypeComboBox;
    private javax.swing.JComboBox<String> cutoffComboBox;
    private javax.swing.JLabel cutoffLabel;
    private javax.swing.JLabel loanDeductionLabel;
    private javax.swing.JLabel timeRecordLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel employeeIdLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel rateLabel;
    private javax.swing.JLabel employeeTypeLabel;
    private javax.swing.JSeparator detailsSeparator;
    private javax.swing.JTextField employeeIdField;
    private javax.swing.JTextField fullNameField;
    private javax.swing.JTextField rateField;
    private javax.swing.JTextField loanDeductionField;
    private com.com253.payrollsystem.GUI.Components.Table timeRecordTable;
    // End of variables declaration//GEN-END:variables
}
