package com.com253.payrollsystem.GUI.Panels;

import com.com253.payrollsystem.Model.PayrollEntry;
import java.util.Locale;

/**
 *
 * @author Jaszi
 */
public class Payslip extends javax.swing.JPanel {

    /**
     * Creates new form EmployeeInfo
     */
    public Payslip() {
        initComponents();
    }

    public void showPayroll(PayrollEntry entry) {
        employeeIdValueLabel.setText(entry.getEmployee().getEmployeeId());
        fullNameValueLabel.setText(entry.getEmployee().getName());
        employeeTypeValueLabel.setText(entry.getEmployee().getEmployeeType());
        cutoffPeriodValueLabel.setText(entry.getCutOffPeriod());

        totalHoursWorkedValueLabel.setText(formatHours(entry.getTotalHoursWorked()));
        overtimeHoursValueLabel.setText(formatHours(entry.getOvertimeHours()));
        undertimeHoursValueLabel.setText(formatHours(entry.getUndertimeHours()));
        absentDaysValueLabel.setText(String.format(Locale.US, "%d day(s)", entry.getAbsentDays()));

        basicSalaryValueLabel.setText(formatMoney(entry.getBasicPay()));
        overtimePayValueLabel.setText(formatMoney(entry.getOvertimePay()));
        grossPayValueLabel.setText(formatMoney(entry.getGrossPay()));

        sssValueLabel.setText(formatMoney(entry.getSssDeduction()));
        philhealthValueLabel.setText(formatMoney(entry.getPhilhealthDeduction()));
        pagibigValueLabel.setText(formatMoney(entry.getPagibigDeduction()));
        withholdingTaxValueLabel.setText(formatMoney(entry.getTaxDeduction()));
        loanDeductionValueLabel.setText(formatMoney(entry.getLoanDeduction()));
        undertimePenaltyValueLabel.setText(formatMoney(entry.getUndertimePenalty()));
        absencePenaltyValueLabel.setText(formatMoney(entry.getAbsencePenalty()));

        netPayValueLabel.setText(formatMoney(entry.getNetPay()));
    }

    public void resetDisplay() {
        employeeIdValueLabel.setText("Employee ID");
        fullNameValueLabel.setText("Full Name");
        employeeTypeValueLabel.setText("Employee Type");
        cutoffPeriodValueLabel.setText("Cut-off Period");

        totalHoursWorkedValueLabel.setText("0.00 hrs");
        overtimeHoursValueLabel.setText("0.00 hrs");
        undertimeHoursValueLabel.setText("0.00 hrs");
        absentDaysValueLabel.setText("0 day(s)");

        basicSalaryValueLabel.setText("PHP 0.00");
        overtimePayValueLabel.setText("PHP 0.00");
        grossPayValueLabel.setText("PHP 0.00");

        sssValueLabel.setText("PHP 0.00");
        philhealthValueLabel.setText("PHP 0.00");
        pagibigValueLabel.setText("PHP 0.00");
        withholdingTaxValueLabel.setText("PHP 0.00");
        loanDeductionValueLabel.setText("PHP 0.00");
        undertimePenaltyValueLabel.setText("PHP 0.00");
        absencePenaltyValueLabel.setText("PHP 0.00");

        netPayValueLabel.setText("PHP 0.00");
    }

    private String formatMoney(double amount) {
        return String.format(Locale.US, "PHP %,.2f", amount);
    }

    private String formatHours(double hours) {
        return String.format(Locale.US, "%.2f hrs", hours);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        employeeIdLabel = new javax.swing.JLabel();
        employeeIdValueLabel = new javax.swing.JLabel();
        fullNameLabel = new javax.swing.JLabel();
        fullNameValueLabel = new javax.swing.JLabel();
        employeeTypeLabel = new javax.swing.JLabel();
        employeeTypeValueLabel = new javax.swing.JLabel();
        cutoffPeriodLabel = new javax.swing.JLabel();
        cutoffPeriodValueLabel = new javax.swing.JLabel();
        headerSeparator = new javax.swing.JSeparator();
        attendanceSummaryLabel = new javax.swing.JLabel();
        totalHoursWorkedLabel = new javax.swing.JLabel();
        totalHoursWorkedValueLabel = new javax.swing.JLabel();
        overtimeHoursLabel = new javax.swing.JLabel();
        overtimeHoursValueLabel = new javax.swing.JLabel();
        undertimeHoursLabel = new javax.swing.JLabel();
        undertimeHoursValueLabel = new javax.swing.JLabel();
        absentDaysLabel = new javax.swing.JLabel();
        absentDaysValueLabel = new javax.swing.JLabel();
        basicSalaryLabel = new javax.swing.JLabel();
        basicSalaryValueLabel = new javax.swing.JLabel();
        salaryDetailsLabel = new javax.swing.JLabel();
        overtimePayLabel = new javax.swing.JLabel();
        overtimePayValueLabel = new javax.swing.JLabel();
        grossPayLabel = new javax.swing.JLabel();
        grossPayValueLabel = new javax.swing.JLabel();
        deductionsSeparator = new javax.swing.JSeparator();
        deductionsHeaderLabel = new javax.swing.JLabel();
        sssLabel = new javax.swing.JLabel();
        philhealthLabel = new javax.swing.JLabel();
        pagibigLabel = new javax.swing.JLabel();
        withholdingTaxLabel = new javax.swing.JLabel();
        sssValueLabel = new javax.swing.JLabel();
        philhealthValueLabel = new javax.swing.JLabel();
        pagibigValueLabel = new javax.swing.JLabel();
        withholdingTaxValueLabel = new javax.swing.JLabel();
        loanDeductionValueLabel = new javax.swing.JLabel();
        loanDeductionLabel = new javax.swing.JLabel();
        undertimePenaltyValueLabel = new javax.swing.JLabel();
        undertimePenaltyLabel = new javax.swing.JLabel();
        absencePenaltyValueLabel = new javax.swing.JLabel();
        absencePenaltyLabel = new javax.swing.JLabel();
        netPaySeparator = new javax.swing.JSeparator();
        netPayLabel = new javax.swing.JLabel();
        netPayValueLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(10, 12, 20));
        setMaximumSize(new java.awt.Dimension(800, 700));

        titleLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setText("PAYSLIP");

        employeeIdLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        employeeIdLabel.setForeground(new java.awt.Color(120, 135, 170));
        employeeIdLabel.setText("Employee ID");

        employeeIdValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        employeeIdValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeeIdValueLabel.setText("Employee ID");

        fullNameLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        fullNameLabel.setForeground(new java.awt.Color(120, 135, 170));
        fullNameLabel.setText("Full Name");

        fullNameValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        fullNameValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        fullNameValueLabel.setText("Full Name");

        employeeTypeLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        employeeTypeLabel.setForeground(new java.awt.Color(120, 135, 170));
        employeeTypeLabel.setText("Employee Type");

        employeeTypeValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        employeeTypeValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeeTypeValueLabel.setText("Employee Type");

        cutoffPeriodLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        cutoffPeriodLabel.setForeground(new java.awt.Color(120, 135, 170));
        cutoffPeriodLabel.setText("Cut-off Period");

        cutoffPeriodValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        cutoffPeriodValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        cutoffPeriodValueLabel.setText("Cut-off Period");

        attendanceSummaryLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        attendanceSummaryLabel.setForeground(new java.awt.Color(255, 255, 255));
        attendanceSummaryLabel.setText("ATTENDANCE SUMMARY");

        totalHoursWorkedLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        totalHoursWorkedLabel.setForeground(new java.awt.Color(120, 135, 170));
        totalHoursWorkedLabel.setText("Total Hours Worked");

        totalHoursWorkedValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        totalHoursWorkedValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        totalHoursWorkedValueLabel.setText("0.00 hrs");

        overtimeHoursLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        overtimeHoursLabel.setForeground(new java.awt.Color(120, 135, 170));
        overtimeHoursLabel.setText("Overtime Hours");

        overtimeHoursValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        overtimeHoursValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        overtimeHoursValueLabel.setText("0.00 hrs");

        undertimeHoursLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        undertimeHoursLabel.setForeground(new java.awt.Color(120, 135, 170));
        undertimeHoursLabel.setText("Undertime Hours");

        undertimeHoursValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        undertimeHoursValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        undertimeHoursValueLabel.setText("0.00 hrs");

        absentDaysLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        absentDaysLabel.setForeground(new java.awt.Color(120, 135, 170));
        absentDaysLabel.setText("Absent Days");

        absentDaysValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        absentDaysValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        absentDaysValueLabel.setText("0 day(s)");

        basicSalaryLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        basicSalaryLabel.setForeground(new java.awt.Color(120, 135, 170));
        basicSalaryLabel.setText("Basic Salary");

        basicSalaryValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        basicSalaryValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        basicSalaryValueLabel.setText("PHP 0.00");

        salaryDetailsLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        salaryDetailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        salaryDetailsLabel.setText("SALARY DETAILS");

        overtimePayLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        overtimePayLabel.setForeground(new java.awt.Color(120, 135, 170));
        overtimePayLabel.setText("Overtime");

        overtimePayValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        overtimePayValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        overtimePayValueLabel.setText("PHP 0.00");

        grossPayLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        grossPayLabel.setForeground(new java.awt.Color(120, 135, 170));
        grossPayLabel.setText("Gross Pay");

        grossPayValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        grossPayValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        grossPayValueLabel.setText("PHP 0.00");

        deductionsHeaderLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        deductionsHeaderLabel.setForeground(new java.awt.Color(255, 255, 255));
        deductionsHeaderLabel.setText("DEDUCTION");

        sssLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        sssLabel.setForeground(new java.awt.Color(120, 135, 170));
        sssLabel.setText("SSS");

        philhealthLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        philhealthLabel.setForeground(new java.awt.Color(120, 135, 170));
        philhealthLabel.setText("PhilHealth");

        pagibigLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        pagibigLabel.setForeground(new java.awt.Color(120, 135, 170));
        pagibigLabel.setText("Pag-IBIG");

        withholdingTaxLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        withholdingTaxLabel.setForeground(new java.awt.Color(120, 135, 170));
        withholdingTaxLabel.setText("Withholding Tax");

        sssValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        sssValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        sssValueLabel.setText("PHP 0.00");

        philhealthValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        philhealthValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        philhealthValueLabel.setText("PHP 0.00");

        pagibigValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        pagibigValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        pagibigValueLabel.setText("PHP 0.00");

        withholdingTaxValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        withholdingTaxValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        withholdingTaxValueLabel.setText("PHP 0.00");

        loanDeductionValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        loanDeductionValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        loanDeductionValueLabel.setText("PHP 0.00");

        loanDeductionLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        loanDeductionLabel.setForeground(new java.awt.Color(120, 135, 170));
        loanDeductionLabel.setText("Loan Deduction");

        undertimePenaltyValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        undertimePenaltyValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        undertimePenaltyValueLabel.setText("PHP 0.00");

        undertimePenaltyLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        undertimePenaltyLabel.setForeground(new java.awt.Color(120, 135, 170));
        undertimePenaltyLabel.setText("Undertime Penalty");

        absencePenaltyValueLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        absencePenaltyValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        absencePenaltyValueLabel.setText("PHP 0.00");

        absencePenaltyLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        absencePenaltyLabel.setForeground(new java.awt.Color(120, 135, 170));
        absencePenaltyLabel.setText("Absence Penalty");

        netPayLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        netPayLabel.setForeground(new java.awt.Color(255, 255, 255));
        netPayLabel.setText("NET PAY");

        netPayValueLabel.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        netPayValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        netPayValueLabel.setText("PHP 0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loanDeductionLabel)
                        .addGap(91, 91, 91)
                        .addComponent(loanDeductionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(absencePenaltyLabel)
                            .addComponent(undertimePenaltyLabel))
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(undertimePenaltyValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(absencePenaltyValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(withholdingTaxLabel)
                            .addGap(88, 88, 88)
                            .addComponent(withholdingTaxValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(pagibigLabel)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pagibigValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sssLabel)
                                .addComponent(philhealthLabel))
                            .addGap(122, 122, 122)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(sssValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(philhealthValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(netPayLabel)
                        .addGap(315, 315, 315)
                        .addComponent(netPayValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(netPaySeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deductionsHeaderLabel)
                    .addComponent(deductionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(employeeTypeLabel)
                                    .addGap(51, 51, 51))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(employeeIdLabel)
                                    .addGap(67, 67, 67))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fullNameLabel)
                                    .addGap(81, 81, 81)))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(fullNameValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeeIdValueLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(employeeTypeValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                        .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(attendanceSummaryLabel)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(absentDaysLabel)
                                        .addGap(108, 108, 108)
                                        .addComponent(absentDaysValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(undertimeHoursLabel)
                                        .addGap(83, 83, 83)
                                        .addComponent(undertimeHoursValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(overtimeHoursLabel)
                                        .addGap(90, 90, 90)
                                        .addComponent(overtimeHoursValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(titleLabel)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cutoffPeriodLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totalHoursWorkedLabel))
                                    .addGap(66, 66, 66)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cutoffPeriodValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(totalHoursWorkedValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(salaryDetailsLabel)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(grossPayLabel)
                                    .addGap(121, 121, 121)
                                    .addComponent(grossPayValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(overtimePayLabel)
                                    .addGap(127, 127, 127)
                                    .addComponent(overtimePayValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(basicSalaryLabel)
                                    .addGap(108, 108, 108)
                                    .addComponent(basicSalaryValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(salaryDetailsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(basicSalaryValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(basicSalaryLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(overtimePayLabel)
                            .addComponent(overtimePayValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grossPayLabel)
                            .addComponent(grossPayValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(titleLabel)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(employeeIdLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fullNameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeTypeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(employeeIdValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fullNameValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(employeeTypeValueLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cutoffPeriodValueLabel)
                            .addComponent(cutoffPeriodLabel))
                        .addGap(18, 18, 18)
                        .addComponent(headerSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attendanceSummaryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalHoursWorkedLabel)
                            .addComponent(totalHoursWorkedValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(overtimeHoursLabel)
                            .addComponent(overtimeHoursValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(undertimeHoursLabel)
                            .addComponent(undertimeHoursValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(absentDaysLabel)
                            .addComponent(absentDaysValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(deductionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deductionsHeaderLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sssLabel)
                    .addComponent(sssValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(philhealthLabel)
                    .addComponent(philhealthValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pagibigLabel)
                    .addComponent(pagibigValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withholdingTaxLabel)
                    .addComponent(withholdingTaxValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanDeductionLabel)
                    .addComponent(loanDeductionValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(undertimePenaltyLabel)
                    .addComponent(undertimePenaltyValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(absencePenaltyLabel)
                    .addComponent(absencePenaltyValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(netPaySeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(netPayLabel)
                    .addComponent(netPayValueLabel))
                .addContainerGap(143, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cutoffPeriodLabel;
    private javax.swing.JLabel totalHoursWorkedLabel;
    private javax.swing.JLabel overtimeHoursLabel;
    private javax.swing.JLabel employeeIdValueLabel;
    private javax.swing.JLabel fullNameValueLabel;
    private javax.swing.JLabel employeeTypeValueLabel;
    private javax.swing.JLabel cutoffPeriodValueLabel;
    private javax.swing.JLabel totalHoursWorkedValueLabel;
    private javax.swing.JLabel overtimeHoursValueLabel;
    private javax.swing.JLabel undertimeHoursLabel;
    private javax.swing.JLabel undertimeHoursValueLabel;
    private javax.swing.JLabel absentDaysLabel;
    private javax.swing.JLabel absentDaysValueLabel;
    private javax.swing.JLabel basicSalaryLabel;
    private javax.swing.JLabel basicSalaryValueLabel;
    private javax.swing.JLabel salaryDetailsLabel;
    private javax.swing.JLabel overtimePayLabel;
    private javax.swing.JLabel overtimePayValueLabel;
    private javax.swing.JLabel grossPayLabel;
    private javax.swing.JLabel grossPayValueLabel;
    private javax.swing.JLabel deductionsHeaderLabel;
    private javax.swing.JLabel sssLabel;
    private javax.swing.JLabel philhealthLabel;
    private javax.swing.JLabel pagibigLabel;
    private javax.swing.JLabel withholdingTaxLabel;
    private javax.swing.JLabel sssValueLabel;
    private javax.swing.JLabel philhealthValueLabel;
    private javax.swing.JLabel pagibigValueLabel;
    private javax.swing.JLabel withholdingTaxValueLabel;
    private javax.swing.JLabel loanDeductionValueLabel;
    private javax.swing.JLabel loanDeductionLabel;
    private javax.swing.JLabel undertimePenaltyValueLabel;
    private javax.swing.JLabel undertimePenaltyLabel;
    private javax.swing.JLabel absencePenaltyValueLabel;
    private javax.swing.JLabel absencePenaltyLabel;
    private javax.swing.JLabel netPayLabel;
    private javax.swing.JLabel netPayValueLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel employeeIdLabel;
    private javax.swing.JLabel fullNameLabel;
    private javax.swing.JLabel attendanceSummaryLabel;
    private javax.swing.JLabel employeeTypeLabel;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JSeparator deductionsSeparator;
    private javax.swing.JSeparator netPaySeparator;
    // End of variables declaration//GEN-END:variables
}
