package com.com253.payrollsystem.GUI;

import com.com253.payrollsystem.Model.Employee;
import com.com253.payrollsystem.Model.PayrollEntry;
import com.com253.payrollsystem.Model.TimeRecord;
import com.com253.payrollsystem.Service.PayrollCalculator;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Jaszi
 */
public class Menu extends javax.swing.JFrame {

    private static final String CARD_INPUT = "INPUT";
    private static final String CARD_PAYSLIP = "PAYSLIP";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());
    private final CardLayout contentCardLayout = new CardLayout();
    private final JPanel contentPanel = new JPanel(contentCardLayout);
    private final com.com253.payrollsystem.GUI.Panels.Payslip payslipPanel = new com.com253.payrollsystem.GUI.Panels.Payslip();

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        configureContentArea();
        wireSidePanelActions();
    }

    private void configureContentArea() {
        contentPanel.setBackground(new java.awt.Color(10, 12, 20));
        contentPanel.setMaximumSize(new java.awt.Dimension(800, 700));
        contentPanel.add(employeeInfo1, CARD_INPUT);
        contentPanel.add(payslipPanel, CARD_PAYSLIP);

        jPanel1.remove(employeeInfo1);
        jPanel1.add(contentPanel);
        contentCardLayout.show(contentPanel, CARD_INPUT);

        jPanel1.revalidate();
        jPanel1.repaint();
    }

    private void wireSidePanelActions() {
        sidePanel1.setActionHandler(new com.com253.payrollsystem.GUI.Components.SidePanel.ActionHandler() {
            @Override
            public void onProcess() {
                processPayrollFromInput();
            }

            @Override
            public void onClear() {
                clearAll();
            }

            @Override
            public void onExit() {
                dispose();
            }
        });
    }

    private void processPayrollFromInput() {
        try {
            Employee employee = employeeInfo1.buildEmployeeFromInput();
            TimeRecord[] records = employeeInfo1.getTimeRecords();
            String cutoffPeriod = employeeInfo1.getCutoffPeriod();
            double loanDeduction = employeeInfo1.getLoanDeduction();

            PayrollEntry entry = PayrollCalculator.buildPayrollEntry(employee, records, cutoffPeriod, loanDeduction);
            payslipPanel.showPayroll(entry);
            contentCardLayout.show(contentPanel, CARD_PAYSLIP);
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Invalid Input", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Unable to process payroll: " + ex.getMessage(), "Processing Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearAll() {
        employeeInfo1.resetInputs();
        payslipPanel.resetDisplay();
        contentCardLayout.show(contentPanel, CARD_INPUT);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        sidePanel1 = new com.com253.payrollsystem.GUI.Components.SidePanel();
        employeeInfo1 = new com.com253.payrollsystem.GUI.Panels.EmployeeInfo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(10, 12, 20));
        jPanel1.setPreferredSize(new java.awt.Dimension(1025, 700));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(sidePanel1);
        jPanel1.add(employeeInfo1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set FlatLaf look and feel */
        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.com253.payrollsystem.GUI.Panels.EmployeeInfo employeeInfo1;
    private javax.swing.JPanel jPanel1;
    private com.com253.payrollsystem.GUI.Components.SidePanel sidePanel1;
    // End of variables declaration//GEN-END:variables
}
