package com.com253.payrollsystem.GUI.Components;

/**
 *
 * @author Jaszi
 */
public class SidePanel extends javax.swing.JPanel {

    /**
     * Creates new form SidePanel
     */
    public SidePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SystemName2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        ActionsLabel2 = new javax.swing.JLabel();
        ProcessButton2 = new javax.swing.JButton();
        ClearButton2 = new javax.swing.JButton();
        ExitButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(16, 20, 35));
        setMaximumSize(new java.awt.Dimension(220, 32767));

        SystemName2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        SystemName2.setForeground(new java.awt.Color(255, 255, 255));
        SystemName2.setText("PAYROLLPAL");

        ActionsLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        ActionsLabel2.setForeground(new java.awt.Color(120, 135, 170));
        ActionsLabel2.setText("ACTIONS");

        ProcessButton2.setBackground(new java.awt.Color(22, 28, 48));
        ProcessButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ProcessButton2.setForeground(new java.awt.Color(255, 255, 255));
        ProcessButton2.setText("PORCESS");
        ProcessButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));
        ProcessButton2.setFocusable(false);

        ClearButton2.setBackground(new java.awt.Color(22, 28, 48));
        ClearButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ClearButton2.setForeground(new java.awt.Color(255, 255, 255));
        ClearButton2.setText("CLEAR");
        ClearButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));
        ClearButton2.setFocusable(false);

        ExitButton2.setBackground(new java.awt.Color(22, 28, 48));
        ExitButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExitButton2.setForeground(new java.awt.Color(255, 255, 255));
        ExitButton2.setText("EXIT");
        ExitButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));
        ExitButton2.setFocusable(false);
        ExitButton2.addActionListener(this::ExitButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ActionsLabel2)
                        .addGap(0, 157, Short.MAX_VALUE))
                    .addComponent(jSeparator3)
                    .addComponent(ProcessButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ClearButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(SystemName2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(SystemName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ActionsLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProcessButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ClearButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ExitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActionsLabel2;
    private javax.swing.JButton ClearButton2;
    private javax.swing.JButton ExitButton2;
    private javax.swing.JButton ProcessButton2;
    private javax.swing.JLabel SystemName2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
