package com.com253.payrollsystem.GUI.Components;

/**
 *
 * @author Jaszi
 */
public class SidePanel extends javax.swing.JPanel {

    public interface ActionHandler {
        void onProcess();
        void onClear();
        void onExit();
    }

    private ActionHandler actionHandler;

    /**
     * Creates new form SidePanel
     */
    public SidePanel() {
        initComponents();
        processButton.addActionListener(this::processButtonActionPerformed);
        clearButton.addActionListener(this::clearButtonActionPerformed);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        systemNameLabel = new javax.swing.JLabel();
        actionsSeparator = new javax.swing.JSeparator();
        actionsLabel = new javax.swing.JLabel();
        processButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(16, 20, 35));
        setMaximumSize(new java.awt.Dimension(220, 32767));

        systemNameLabel.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        systemNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        systemNameLabel.setText("PAYROLLPAL");

        actionsLabel.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        actionsLabel.setForeground(new java.awt.Color(120, 135, 170));
        actionsLabel.setText("ACTIONS");

        processButton.setBackground(new java.awt.Color(22, 28, 48));
        processButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        processButton.setForeground(new java.awt.Color(255, 255, 255));
        processButton.setText("PROCESS");
        processButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));
        processButton.setFocusable(false);
        processButton.addActionListener(this::processButtonActionPerformed);

        clearButton.setBackground(new java.awt.Color(22, 28, 48));
        clearButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clearButton.setForeground(new java.awt.Color(255, 255, 255));
        clearButton.setText("CLEAR");
        clearButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));
        clearButton.setFocusable(false);

        exitButton.setBackground(new java.awt.Color(22, 28, 48));
        exitButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitButton.setForeground(new java.awt.Color(255, 255, 255));
        exitButton.setText("EXIT");
        exitButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(40, 50, 80)));
        exitButton.setFocusable(false);
        exitButton.addActionListener(this::exitButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(systemNameLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(actionsLabel)
                                .addGap(0, 157, Short.MAX_VALUE))
                            .addComponent(actionsSeparator, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(processButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(systemNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionsSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(actionsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(processButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(489, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        if (actionHandler != null) {
            actionHandler.onExit();
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        if (actionHandler != null) {
            actionHandler.onProcess();
        }
    }//GEN-LAST:event_processButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (actionHandler != null) {
            actionHandler.onClear();
        }
    }

    public void setActionHandler(ActionHandler actionHandler) {
        this.actionHandler = actionHandler;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel actionsLabel;
    private javax.swing.JSeparator actionsSeparator;
    private javax.swing.JButton clearButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton processButton;
    private javax.swing.JLabel systemNameLabel;
    // End of variables declaration//GEN-END:variables
}
