package com.com253.payrollsystem.GUI.Components;

import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;

/**
 *
 * @author Jaszi
 */
public class Table extends javax.swing.JPanel {

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
        configureTimeRecordTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setBackground(new java.awt.Color(22, 28, 48));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Day", "Time in", "Time out", "Absent", "Holiday Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(40, 50, 80));
        jTable1.setRowHeight(32);
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(220);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configureTimeRecordTable() {
        String[] dayLabels = new String[15];
        for (int i = 0; i < dayLabels.length; i++) {
            dayLabels[i] = "Day " + (i + 1);
        }

        DefaultTableModel model = new DefaultTableModel(
            new Object[dayLabels.length][5],
            new String[]{"Day", "Time in", "Time out", "Absent", "Holiday Type"}
        ) {
            private final Class<?>[] columnTypes = new Class[]{
                String.class, String.class, String.class, Boolean.class, String.class
            };
            private final boolean[] editableColumns = new boolean[]{
                false, true, true, true, true
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnTypes[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return editableColumns[column];
            }
        };

        for (int i = 0; i < dayLabels.length; i++) {
            model.setValueAt(dayLabels[i], i, 0);
            model.setValueAt("0900", i, 1);
            model.setValueAt("1700", i, 2);
            model.setValueAt(Boolean.FALSE, i, 3);
            model.setValueAt("Regular Day", i, 4);
        }

        jTable1.setModel(model);

        jTable1.getColumnModel().getColumn(1).setCellEditor(new TimeComboCellEditor("0900"));
        jTable1.getColumnModel().getColumn(2).setCellEditor(new TimeComboCellEditor("1700"));

        JComboBox<String> holidayTypeCombo = new JComboBox<>(new String[]{
            "Regular Day",
            "Regular Holiday",
            "Special Holiday / Rest Day"
        });
        jTable1.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(holidayTypeCombo));

        DefaultTableCellRenderer centeredTextRenderer = new DefaultTableCellRenderer() {
            @Override
            protected void setValue(Object value) {
                if (value == null) {
                    super.setValue("");
                    return;
                }

                String raw = value.toString();
                if (raw.matches("\\d{4}")) {
                    super.setValue(formatDisplayTime(raw));
                } else {
                    super.setValue(raw);
                }
            }
        };
        centeredTextRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centeredTextRenderer);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(centeredTextRenderer);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(centeredTextRenderer);

        jTable1.getColumnModel().getColumn(0).setPreferredWidth(120);
        jTable1.getColumnModel().getColumn(1).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(2).setPreferredWidth(140);
        jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
    }

    private String formatDisplayTime(String militaryTime) {
        int hour24 = Integer.parseInt(militaryTime.substring(0, 2));
        String minute = militaryTime.substring(2, 4);
        String period = hour24 >= 12 ? "PM" : "AM";
        int hour12 = hour24 % 12;
        if (hour12 == 0) {
            hour12 = 12;
        }
        return String.format("%d:%s %s", hour12, minute, period);
    }

    private static class TimeComboCellEditor extends AbstractCellEditor implements TableCellEditor {
        private final JPanel editorPanel;
        private final JComboBox<String> hourCombo;
        private final JComboBox<String> minuteCombo;
        private final String defaultTime;

        TimeComboCellEditor(String defaultTime) {
            this.defaultTime = defaultTime;
            this.editorPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 4, 0));
            this.editorPanel.setOpaque(true);
            this.editorPanel.setBackground(new java.awt.Color(22, 28, 48));

            this.hourCombo = new JComboBox<>();
            for (int hour = 0; hour < 24; hour++) {
                hourCombo.addItem(String.format("%02d", hour));
            }

            this.minuteCombo = new JComboBox<>();
            for (int minute = 0; minute < 60; minute++) {
                minuteCombo.addItem(String.format("%02d", minute));
            }

            hourCombo.setBackground(new java.awt.Color(22, 28, 48));
            minuteCombo.setBackground(new java.awt.Color(22, 28, 48));
            hourCombo.setForeground(new java.awt.Color(255, 255, 255));
            minuteCombo.setForeground(new java.awt.Color(255, 255, 255));

            editorPanel.add(hourCombo);
            editorPanel.add(new JLabel(":"));
            editorPanel.add(minuteCombo);
        }

        @Override
        public Object getCellEditorValue() {
            int hour24 = Integer.parseInt((String) hourCombo.getSelectedItem());
            int minute = Integer.parseInt((String) minuteCombo.getSelectedItem());

            return String.format("%02d%02d", hour24, minute);
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            String militaryTime = value != null ? value.toString() : defaultTime;
            if (!militaryTime.matches("\\d{4}")) {
                militaryTime = defaultTime;
            }

            int hour24 = Integer.parseInt(militaryTime.substring(0, 2));
            String minute = militaryTime.substring(2, 4);

            hourCombo.setSelectedItem(String.format("%02d", hour24));
            minuteCombo.setSelectedItem(minute);

            return editorPanel;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
