package com.com253.payrollsystem.GUI.Components;

import com.com253.payrollsystem.Model.TimeRecord;
import java.awt.Component;
import java.awt.FlowLayout;
import javax.swing.AbstractCellEditor;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;

/**
 *
 * @author Jaszi
 */
public class Table extends javax.swing.JPanel {

    private int[] workingDays = new int[0];

    /**
     * Creates new form Table
     */
    public Table() {
        initComponents();
        setWorkingDays(createDefaultWorkingDays());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        timeRecordScrollPane = new javax.swing.JScrollPane();
        timeRecordTable = new javax.swing.JTable();

        timeRecordTable.setBackground(new java.awt.Color(22, 28, 48));
        timeRecordTable.setForeground(new java.awt.Color(255, 255, 255));
        timeRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Day", "Time in", "Time out", "Absent", "Holiday Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        timeRecordTable.setGridColor(new java.awt.Color(40, 50, 80));
        timeRecordTable.setRowHeight(32);
        timeRecordTable.setSelectionForeground(new java.awt.Color(255, 255, 255));
        timeRecordScrollPane.setViewportView(timeRecordTable);
        if (timeRecordTable.getColumnModel().getColumnCount() > 0) {
            timeRecordTable.getColumnModel().getColumn(0).setPreferredWidth(30);
            timeRecordTable.getColumnModel().getColumn(3).setPreferredWidth(180);
            timeRecordTable.getColumnModel().getColumn(3).setMaxWidth(220);
            timeRecordTable.getColumnModel().getColumn(4).setPreferredWidth(90);
            timeRecordTable.getColumnModel().getColumn(4).setMaxWidth(90);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeRecordScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(timeRecordScrollPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void configureTimeRecordTable(int[] days) {
        String[] dayLabels = new String[days.length];
        for (int i = 0; i < dayLabels.length; i++) {
            dayLabels[i] = "Day " + days[i];
        }

        DefaultTableModel model = new DefaultTableModel(
            new Object[dayLabels.length][5],
            new String[]{"Day", "Time in", "Time out", "Absent", "Holiday Type"}
        ) {
            private final Class<?>[] columnTypes = new Class[]{
                String.class, String.class, String.class, Boolean.class, String.class
            };
            private final boolean[] editableColumns = new boolean[]{
                false, true, true, true, true
            };

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return columnTypes[columnIndex];
            }

            @Override
            public boolean isCellEditable(int row, int column) {
                return editableColumns[column];
            }
        };

        for (int i = 0; i < dayLabels.length; i++) {
            model.setValueAt(dayLabels[i], i, 0);
            model.setValueAt("0800", i, 1);
            model.setValueAt("1700", i, 2);
            model.setValueAt(Boolean.FALSE, i, 3);
            model.setValueAt("Regular Day", i, 4);
        }

        timeRecordTable.setModel(model);

        timeRecordTable.getColumnModel().getColumn(1).setCellEditor(new TimeComboCellEditor("0800"));
        timeRecordTable.getColumnModel().getColumn(2).setCellEditor(new TimeComboCellEditor("1700"));

        JComboBox<String> holidayTypeCombo = new JComboBox<>(new String[]{
            "Regular Day",
            "Regular Holiday",
            "Special Holiday / Rest Day"
        });
        timeRecordTable.getColumnModel().getColumn(4).setCellEditor(new DefaultCellEditor(holidayTypeCombo));

        DefaultTableCellRenderer centeredTextRenderer = new DefaultTableCellRenderer() {
            @Override
            protected void setValue(Object value) {
                if (value == null) {
                    super.setValue("");
                    return;
                }

                String raw = value.toString();
                if (raw.matches("\\d{4}")) {
                    super.setValue(formatDisplayTime(raw));
                } else {
                    super.setValue(raw);
                }
            }
        };
        centeredTextRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        timeRecordTable.getColumnModel().getColumn(0).setCellRenderer(centeredTextRenderer);
        timeRecordTable.getColumnModel().getColumn(1).setCellRenderer(centeredTextRenderer);
        timeRecordTable.getColumnModel().getColumn(2).setCellRenderer(centeredTextRenderer);

        timeRecordTable.getColumnModel().getColumn(0).setPreferredWidth(120);
        timeRecordTable.getColumnModel().getColumn(1).setPreferredWidth(140);
        timeRecordTable.getColumnModel().getColumn(2).setPreferredWidth(140);
        timeRecordTable.getColumnModel().getColumn(4).setPreferredWidth(90);
    }

    public TimeRecord[] buildTimeRecords() {
        DefaultTableModel model = (DefaultTableModel) timeRecordTable.getModel();
        TimeRecord[] records = new TimeRecord[model.getRowCount()];

        for (int row = 0; row < model.getRowCount(); row++) {
            int dayNumber = workingDays[row];
            boolean isAbsent = parseAbsentFlag(model.getValueAt(row, 3));
            if (isAbsent) {
                records[row] = new TimeRecord(dayNumber, 0, 0, true, TimeRecord.HOLIDAY_NONE);
                continue;
            }

            int timeIn = parseTimeToHHMM(model.getValueAt(row, 1), "Time in", dayNumber);
            int timeOut = parseTimeToHHMM(model.getValueAt(row, 2), "Time out", dayNumber);

            if (timeOut <= timeIn) {
                throw new IllegalArgumentException("Day " + dayNumber + ": Time out must be later than Time in.");
            }

            String holiday = mapHolidayType(model.getValueAt(row, 4), dayNumber);

            records[row] = new TimeRecord(
                dayNumber,
                timeIn,
                timeOut,
                isAbsent,
                holiday
            );
        }

        return records;
    }

    public void resetToDefaults() {
        configureTimeRecordTable(workingDays);
    }

    public void setWorkingDays(int[] workingDays) {
        if (workingDays == null || workingDays.length == 0) {
            throw new IllegalArgumentException("Working days cannot be empty.");
        }

        this.workingDays = workingDays.clone();
        configureTimeRecordTable(this.workingDays);
    }

    private int parseTimeToHHMM(Object value, String fieldName, int dayNumber) {
        if (value == null) {
            throw new IllegalArgumentException("Day " + dayNumber + ": " + fieldName + " is required.");
        }

        String raw = value.toString().trim();
        if (!raw.matches("\\d{4}")) {
            throw new IllegalArgumentException(
                "Day " + dayNumber + ": " + fieldName + " must be in HHMM format (e.g., 0800)."
            );
        }

        int hour = Integer.parseInt(raw.substring(0, 2));
        int minute = Integer.parseInt(raw.substring(2, 4));
        if (hour < 0 || hour > 23 || minute < 0 || minute > 59) {
            throw new IllegalArgumentException(
                "Day " + dayNumber + ": " + fieldName + " must be a valid 24-hour time."
            );
        }

        return Integer.parseInt(raw);
    }

    private boolean parseAbsentFlag(Object value) {
        if (value instanceof Boolean) {
            return (Boolean) value;
        }
        if (value == null) {
            return false;
        }
        return Boolean.parseBoolean(value.toString());
    }

    private String mapHolidayType(Object value, int dayNumber) {
        String text = value == null ? "Regular Day" : value.toString();
        return switch (text) {
            case "Regular Holiday" -> TimeRecord.HOLIDAY_REGULAR;
            case "Special Holiday / Rest Day" -> TimeRecord.HOLIDAY_REST_DAY;
            case "Regular Day" -> TimeRecord.HOLIDAY_NONE;
            default -> throw new IllegalArgumentException("Day " + dayNumber + ": Invalid holiday type.");
        };
    }

    private int[] createDefaultWorkingDays() {
        int[] defaults = new int[15];
        for (int i = 0; i < defaults.length; i++) {
            defaults[i] = i + 1;
        }
        return defaults;
    }

    private String formatDisplayTime(String militaryTime) {
        int hour24 = Integer.parseInt(militaryTime.substring(0, 2));
        String minute = militaryTime.substring(2, 4);
        String period = hour24 >= 12 ? "PM" : "AM";
        int hour12 = hour24 % 12;
        if (hour12 == 0) {
            hour12 = 12;
        }
        return String.format("%d:%s %s", hour12, minute, period);
    }

    private static class TimeComboCellEditor extends AbstractCellEditor implements TableCellEditor {
        private final JPanel editorPanel;
        private final JComboBox<String> hourCombo;
        private final JComboBox<String> minuteCombo;
        private final String defaultTime;

        TimeComboCellEditor(String defaultTime) {
            this.defaultTime = defaultTime;
            this.editorPanel = new JPanel(new FlowLayout(FlowLayout.CENTER, 4, 0));
            this.editorPanel.setOpaque(true);
            this.editorPanel.setBackground(new java.awt.Color(22, 28, 48));

            this.hourCombo = new JComboBox<>();
            for (int hour = 0; hour < 24; hour++) {
                hourCombo.addItem(String.format("%02d", hour));
            }

            this.minuteCombo = new JComboBox<>();
            for (int minute = 0; minute < 60; minute++) {
                minuteCombo.addItem(String.format("%02d", minute));
            }

            hourCombo.setBackground(new java.awt.Color(22, 28, 48));
            minuteCombo.setBackground(new java.awt.Color(22, 28, 48));
            hourCombo.setForeground(new java.awt.Color(255, 255, 255));
            minuteCombo.setForeground(new java.awt.Color(255, 255, 255));

            editorPanel.add(hourCombo);
            editorPanel.add(new JLabel(":"));
            editorPanel.add(minuteCombo);
        }

        @Override
        public Object getCellEditorValue() {
            int hour24 = Integer.parseInt((String) hourCombo.getSelectedItem());
            int minute = Integer.parseInt((String) minuteCombo.getSelectedItem());

            return String.format("%02d%02d", hour24, minute);
        }

        @Override
        public Component getTableCellEditorComponent(JTable table, Object value, boolean isSelected, int row, int column) {
            String militaryTime = value != null ? value.toString() : defaultTime;
            if (!militaryTime.matches("\\d{4}")) {
                militaryTime = defaultTime;
            }

            int hour24 = Integer.parseInt(militaryTime.substring(0, 2));
            String minute = militaryTime.substring(2, 4);

            hourCombo.setSelectedItem(String.format("%02d", hour24));
            minuteCombo.setSelectedItem(minute);

            return editorPanel;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane timeRecordScrollPane;
    private javax.swing.JTable timeRecordTable;
    // End of variables declaration//GEN-END:variables
}
